### ISSUE TITLE
Allow string values for order parameter in rule

### ISSUE THREAD

**Issue by gmenuel** [kemra102/puppet-auditd#15]
Hi !

Is there a reason for enforcing the use of a numeric type for the order parameter in auditd::rule ? According to the concat module documentation the order parameter can be a string or an integer.

Regards.

**Comment by kemra102** [comment]
Purely because I wanted to validate input and assuming a numeric here is logical given what it is being used for.

Is there a reason you would need to order based on strings instead?

**Comment by kemra102** [comment]
Haven't had a response for a weeks so I'm going to close this issue. If you need to re-open it feel free to do so.
