### ISSUE TITLE
It crashes when a different path for the rules is used

### ISSUE THREAD

**Issue by fabianfrz** [kemra102/puppet-auditd#16]
When I set rules_file to something different, it does not work.

It works when
- I don't set the rules_file
- I set it to the default value

It does not work:
- when a different path is used

What exactly happens:
The file gets written without the rules.

Tested on CentOS 7

**Comment by kemra102** [comment]
The file is likely empty due to the way the concat fragments are looking up the path to the rules file.

Although to the best of my knowledge it isn't possible to use arbitrary locations for the rules file and still have it read by auditd as none of the tools around auditd allow specifying the path.

**Comment by fabianfrz** [comment]
The problem is that I want to add different rule sets to different servers and when auditd is started, the files are concatenated on CentOS. So one puppet file should manage the service and the others contain the rules. For example, if it is an web server, a puppet file containing auditd rules for the web server is used additionally. The only thing that needs to be changed is the file name but not the base path.

**Comment by kemra102** [comment]
If you want to add different rule sets based on role you should use Hiera to set your rules based on those rules in all likelihood.

**Comment by kemra102** [comment]
Closing this as haven't had a response for a couple of weeks, please feel free to re-open if required.

**Comment by fabianfrz** [comment]
It is still non-functional:
```
2017-01-09 07:33:41.668393 WARN  puppetlabs.facter - locale environment variables were bad; continuing with LANG=C LC_ALL=C
Warning: Could not find resource 'Concat[audit-file]' in parameter 'before'
   (at /etc/puppetlabs/code/environments/production/modules/auditd/manifests/init.pp:459)
Notice: Compiled catalog for *********.localdomain in environment production in 0.42 seconds
Warning: /Stage[main]/Auditd/Auditd::Rule[use the same namespace or disconnect the app from the old one]/Concat::Fragment[auditd_fragment_use the same namespace or disconnect the app from the old one]/Concat_fragment[auditd_fragment_use the same namespace or disconnect the app from the old one]: Target Concat_file with path of /etc/audit/rules.d/puppet.rules not found in the catalog
Notice: /Stage[main]/Auditd/File[/etc/audit/auditd.conf]/content: content changed '{md5}9b84676fab938b11ac4da4fbda1d2c40' to '{md5}cb1441daafbf110a8ef619c89756a325'
```

using this manifest:
```
class { 'auditd':
  log_file => '/var/log/audit/audit.log',
  manage_audit_files => false,
  rules_file => "/etc/audit/rules.d/other_filename.rules",
  manage_service => false,
  rules => {
    'use the same namespace or disconnect the app from the old one' => {
      content => '-a always,exit -F arch=b64 -S execve',
      order   => '01'
    }
  }
}
```

**Comment by fabianfrz** [comment]
sorry, but I cannot reopen the ticket - you will have to do that by yourself
