### ISSUE TITLE
Allow to disable fragment 0

### ISSUE THREAD

**Issue by fabianfrz** [kemra102/puppet-auditd#20]
It is the file containing the static header so this header does not need to be removed via exec.

It would delete the rules while using multiple auditd configuration files when audit concatenates them.

**Comment by kemra102** [comment]
Can you be more clear about what your issue is exactly? I don't follow the bulk of your post.

The title is straight forward enough though I am not sure what the benefit is - pull requests are of course welcome.

**Comment by fabianfrz** [comment]
This line her will delete all rules from auditd:
https://github.com/kemra102/puppet-auditd/blob/master/templates/audit.rules.begin.fragment.erb#L2

If you want to create a configuration like this:
base.pp
service.pp

service.pp will delete the rules from base.pp because of the "-D" on top of each file

**Comment by kemra102** [comment]
```
This line her will delete all rules from auditd:
https://github.com/kemra102/puppet-auditd/blob/master/templates/audit.rules.begin.fragment.erb#L2
```
Correct
```
If you want to create a configuration like this:
base.pp
service.pp

service.pp will delete the rules from base.pp because of the "-D" on top of each file
```
Was this supposed to link to something? There is no `base.pp` or `service.pp` in this module.

Just guessing as to what may be in these files, I don't see any way in which the rules will be deleted more than once as the initial concat fragment only gets written once.

Again my apologies but it's not clear to me what is being asked here.

**Comment by fabianfrz** [comment]
Those files are an example of how to create the rules with multiple puppet manifests so you have a manifest for the system itself and some for the other stuff. When you do that, each will generate a rules file and each will have the `-D` on top. When auditd is started, it will concatenate all files is the rules directory.
