### ISSUE TITLE
Enable auditctl to continue adding rules even if it find errors in some of them

### ISSUE THREAD

**Issue by jhonny-oliveira** [kemra102/puppet-auditd#36]
Hi!

We would like to set audit rules for a default set of components/packages, if the package is installed we audit it, otherwise, we ignore it.

Would it be possible to add the "-c" flag to "audit.rules.begin.fragment.erb" to allow auditctl to continue adding rules even if it find errors in some of them?

**Comment by kemra102** [comment]
This should not be fixed by #37
