### ISSUE TITLE
Custom rules file location breaks module

### ISSUE THREAD

**Issue by dmnfortytwo** [kemra102/puppet-auditd#42]
How to reproduce: 
add to hiera (or to class call): `auditd::rules_file: /etc/audit/rules.d/audit.rules`
What is expected:
puppet applies ok, rules are stored in `/etc/audit/rules.d/audit.rules`
What really happens:
`Warning: /Stage[main]/Auditd/Auditd::Rule[ignore exe=/bin/uname]/Concat::Fragment[auditd_fragment_ignore exe=/bin/uname]/Concat_fragment[auditd_fragment_ignore exe=/bin/uname]: Target Concat_file with path of /etc/audit/audit.rules not found in the catalog
`
How to fix:
```--- rule_orig.pp        2018-03-12 14:02:17.505500363 +0000
+++ rule.pp     2018-03-12 14:02:29.705495750 +0000
@@ -13,7 +13,7 @@
   validate_string($body)
 
   concat::fragment{ "auditd_fragment_${name}":
-    target  => $auditd::params::rules_file,
+    target  => $auditd::rules_file,
     order   => $order,
     content => $body,
   }
```

**Comment by kemra102** [comment]
This should be fixed after merging #43 - if not please re-open.
