### ISSUE TITLE
Fragments directory is empty

### ISSUE THREAD

**Issue by stavrosicsd** [kemra102/puppet-auditd#5]
I tried to use your module in a fresh Debian Wheezy machine but I get the following error:

Notice: /Stage[main]/Auditd/Concat[/etc/audit/audit.rules]/Exec[concat_/etc/audit/audit.rules]/returns: /var/lib/puppet/concat/bin/concatfragments.rb:112:in `<main>': The fragments directory is empty, cowardly refusing to make empty config files (RuntimeError)
Error: /var/lib/puppet/concat/bin/concatfragments.rb -o "/var/lib/puppet/concat/_etc_audit_audit.rules/fragments.concat.out" -d "/var/lib/puppet/concat/_etc_audit_audit.rules" -w '# This file is managed by Puppet. DO NOT EDIT.' -l returned 1 instead of one of [0]
Error: /Stage[main]/Auditd/Concat[/etc/audit/audit.rules]/Exec[concat_/etc/audit/audit.rules]/returns: change from notrun to 0 failed: /var/lib/puppet/concat/bin/concatfragments.rb -o "/var/lib/puppet/concat/_etc_audit_audit.rules/fragments.concat.out" -d "/var/lib/puppet/concat/_etc_audit_audit.rules" -w '# This file is managed by Puppet. DO NOT EDIT.' -l returned 1 instead of one of [0]

Can you please assist?

**Comment by stavrosicsd** [comment]
Ok the issue is that I wanted to start without any rule. I just called the auditd class without any rule set.

**Comment by kemra102** [comment]
Calling the class without any ruleset is unsupported. I don't see this changing at any point as I can't imagine a situation where you wouldn't want to manage any rules (that really is the main point of the module).
