### ISSUE TITLE
audisp config management?

### ISSUE THREAD

**Issue by salderma** [kemra102/puppet-auditd#6]
Hi, you have an excellent looking module here, thank you for your work!  I wanted to ask if you have any thoughts on adding the ability to manage config files for audisp?

For instance the ability to enable the syslog plugin or any other details that might be important.

**Comment by kemra102** [comment]
That certainly sounds like a good idea, I'll look into it. If you have any resources or documentation you'd like to share please do so.

**Comment by salderma** [comment]
Unfortunately, I'm just getting started into this arena.  I do have a requirement to configure audit message delivery to syslog via audisp, but I have yet to dive into it.  If I can make any headway I'll post it here, or send a PR.

**Comment by salderma** [comment]
For what it's worth, it looks like there's a module that's doing the audisp stuff that might be worth looking at:

https://github.com/simp/pupmod-simp-auditd

**Comment by kemra102** [comment]
I had forgotten about tha NSA puppet modules, I'll use that as a reference and have at least a draft done this weekend for audispd support.

**Comment by kemra102** [comment]
WIP starting here: 1cb9f1c16d76e7059b6d71c432fa3572369ebff7

**Comment by kemra102** [comment]
The **master** branch now has support for Audisp plugins, can you test from the master branch in Git to see if it meets your needs? If any tweaks are required I'd prefer to get them done before doing an official release on the Puppet Forge.

**Comment by salderma** [comment]
Will do!  Thanks for the effort.  It will take me a bit to get a test going, but I should be able to get back to you next week.

**Comment by jordanconway** [comment]
This is working for me on EL7.

**Comment by kemra102** [comment]
All the vagrant smoke tests pass and the puppet-rspec tests all pass so I'm calling this feature done for now. @salderma if you find anything missing you need just raise another issue, I'm happy to do a small point release if there's anything else.
