### ISSUE TITLE
rules

### ISSUE THREAD

**Issue by bnolf** [kemra102/puppet-auditd#9]
I'm new to puppet and I'm trying to use your puppet class with Red Hat Satellite 6.  Satellite 6 allows you to edit the parameters for the module.  I'm trying to set up the rules parameter.  I've tried every example I can find but it doesn't work.  Can you PLEASE provide me an example of a audit rule for this parameter or better yet is there a script that will convert a standard unix audit.rules file to the hash needed for this to work.  Thank you so much.

**Comment by kemra102** [comment]
Hi @bnolf,

I have never used Satallite Server or have access to one so not sure what it is Satellite is expecting. Can you perhaps provide an example of config for something else that uses the same mechanism?

**Comment by bnolf** [comment]
The satellite server is expecting a "hash" data type for the rules for the parameters.  The Sat Server using standard linux audit rules.   I was able to copy the linux audit.rules file into the template,
audit.rules.begin.fragment.erb and it works.  I don't know if this is the best way to do this but it works.

thanks

**Comment by kemra102** [comment]
I suppose something like the following example from the docs:

```puppet
auditd::rule { 'watch for updates to users':
  content => '-w /etc/passwd -p wa -k identity',
  order   => '01',
}
```

Would become something like this:

```ruby
{ content => '-w /etc/passwd -p wa -k identity', order   => '01' }
```

to an `auditd::rule`. Im not sure how you specify the name in Satellite (which is important in this case), again an example of some data entered into Satellite into the normal way would be great.

I would not recommend updating the templates themselves personally but of course you are free to do so.
